; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
monitor_speed = 115200 

[platformio]
src_dir=ardustim

[env:diecimilaatmega328]
platform = atmelavr
board = diecimilaatmega328
framework = arduino
build_src_filter =
    +<*>
    -<esp32_hal.cpp>
    -<esp32_c6_hal.cpp>

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
build_src_filter =
    +<*>
    -<esp32_hal.cpp>
    -<esp32_c6_hal.cpp>

[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_src_filter =
    +<*>
    -<esp32_hal.cpp>
    -<esp32_c6_hal.cpp>

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter =
    +<*>
    -<avr_hal.cpp>
    -<esp32_c6_hal.cpp>

[env:esp32c6]
platform = espressif32
board = esp32-c6-devkitc-1
framework = arduino
build_flags = -DESP32C6
build_src_filter =
    +<*>
    -<avr_hal.cpp>
    -<esp32_hal.cpp>